apiVersion: v2
name: ocr
description: Text recognition application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: minio
  version: "8.0.10"
  repository: "https://helm.min.io/"
  condition: minio.enabled