name: Publish artifacts

on:
  push:
    branches: [ main ]

jobs:       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Set env
      run: echo "RELEASE_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Init
      run: |
        make init

    - name: Containers
      run: |
        make containers DTAG=${{ env.RELEASE_TAG }}

    - name: Bundle
      run: |
        make bundle
  
    - name: Publish
      uses: actions/upload-artifact@v2.2.2
      with: 
        name: application.ocr
        path: bin/bundle